title: Aisha Aijaz
logo: "/assets/aisha.png"
#description: PhD Scholar at IIITD
#show_downloads: true
theme: jekyll-theme-minimal
linkedin: https://www.linkedin.com/in/aishaaijazahmad/
#what are the other themes?
#architect, cayman, dinky, hacker, leap day, merlot, midnight, minimal, minimal, modernist, slate, tactile, time machine
